version: "3.5"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: streatech-ui
    image: streatech-ui
    ports:
      - 4200:4200
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - sourcetree:/app
    # network_mode: host
    
volumes:
  sourcetree:


