version: "3.5"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: techaid-ui
    image: techaid-ui
    ports:
      - 4200:4200
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - sourcetree:/app/node_modules
      - ./:/app
    networks:
      - cta_network

volumes:
  sourcetree:

#connect to techaid server network. Make sure techaid server containers are up before this
networks:
  cta_network:
    name: techaid-server_default
    external: true


