version: "3.5"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streatech-ui
    image: streatech-ui
    ports:
      - 9000:80
    volumes:
      - ./nginx.local.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
