jobs:
    build:
        working_directory: ~/app
        docker:
            - image: circleci/node:12.16.3
        steps:
            - checkout
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - run:
                name: Install local dependencies
                command: npm install
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            - run:
                name: Building
                command: npm run build
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
                    - Dockerfile
                    - nginx.conf
    deploy:
        working_directory: ~/app
        docker:
        - image: alpine:3.6
        steps:
        - checkout
        - run: apk add --no-cache git openssh-client
        - run: mkdir -p ~/.ssh
        - run: ssh-keyscan "app.communitytechaid.org.uk" >> ~/.ssh/known_hosts
        - run: git push ssh://dokku@app.communitytechaid.org.uk/app HEAD:refs/heads/master

version: 2.1
workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build
        - deploy:
            context: global
            requires:
              - build
            filters:
              branches:
                only:
                  - master
