apiVersion: v1
kind: Service
metadata:
  name: stretech-ui-svc
  namespace: apps
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: stretech-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: stretech-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stretech-ui
  template:
    metadata:
      labels:
        app: stretech-ui
    spec:
      imagePullSecrets:
        - name: gcr-regcred
      containers:
        - image: eu.gcr.io/retinue-io/stretech-ui:latest
          name: stretech-ui
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 100
            timeoutSeconds: 5
